ChangeSys/urls.py
from django.contrib import admin
from django.urls import path,include
from django.http import HttpResponse
from change_management import views
from django.urls import  converters

urlpatterns = [
    # path('admin/', admin.site.urls),
    path("",include('change_management.urls',namespace='index_home')),
    path("", include('change_management.urls',namespace='change_management')),
    path("", include('change_implementation.urls',namespace='change_implementation')),
    # path("change_management1/", include('change_management.urls',namespace='change_management1')),
    # path("change_management2/", include('change_management.urls','change_management')),

]

change_implementation/urls.py
#encoding:utf-8
from django.urls import path,re_path
from . import views

app_name = 'change_implementation'
urlpatterns = [
    # path('',views.book,name='index'),
    # path('login/',views.login,name='signin'),
    # path('book_lis/<book_id>/<category_id>/', views.book_lis,name='book_lis'),
    # path('book_author/', views.book_author,name='book_author'),
    # #path('book_publisher/<path:publisher_id>', views.book_publisher,name ='book_publisher'),
    # re_path(r'^book_publisher/(?P<publisher_id>\d{4})/$',views.book_publisher),
    # path('booklist',views.booklist,name='bklist'),
    # path('booklist/page/<int:page>/',views.booklist,name = 'page'),
    # path('index/',views.index,name ='index2'),
    path('change_implementation/', views.change_implementation, name='implementation'),
]

change_management/urls.py
#encoding:utf-8
from django.urls import path,re_path
from . import views

app_name = 'change_management'

urlpatterns = [
    # path('',views.book,name='index'),
    # path('login/',views.login,name='signin'),
    # path('book_lis/<book_id>/<category_id>/', views.book_lis,name='book_lis'),
    # path('book_author/', views.book_author,name='book_author'),
    # #path('book_publisher/<path:publisher_id>', views.book_publisher,name ='book_publisher'),
    # re_path(r'^book_publisher/(?P<publisher_id>\d{4})/$',views.book_publisher),
    # path('booklist',views.booklist,name='bklist'),
    # path('booklist/page/<int:page>/',views.booklist,name = 'page'),
    # path('index/',views.index,name ='index2'),
    path('',views.changemanagement,name='index_management'),
    path('changemanagement/',views.changemanagement, name='management'),
    path('changemanagement_add/',views.changemanagement_add, name='changemanagement_add'),
    path('changemanagement_delete/', views.changemanagement_delete, name='changemanagement_delete'),
]

change_implementation/models.py
from django.db import models

# Create your models here.

change_management/models.py
from django.db import models

# Create your models here.
# class changemeng(models.Model):
#         id =models.AutoField

change_implementation/views.py
from django.shortcuts import render
from datetime import datetime

# Create your views here.
def change_implementation(request):
    connect={
        'books':[
            {
                'name'  :'三国演义',
                'author':'罗贯中',
                'price' : 55.343254,
                'tody': datetime.now(),
            },
            {
                'name'  :'茶花女',
                'author':'小杜马',
                'price' : 60.503953,
                'tody': datetime.now(),
             },
            {
                'name'  :'西游记',
                'author':'吴承恩',
                'price' : 100.49553,
                'tody': datetime.now(),
             },
            {
                'name'  :'红楼梦',
                'author':'曹雪芹',
                'price' : 90.943534,
                #'tody': datetime.now(),
             },
            {
                'name': '葫芦娃',
                'author': '曹雪芹',
                'price': 60.943534,
                'tody': datetime(year=2019,month=3,day=14,hour=11,minute=1,second=0),
            },
        ],
        'person':{
            'use':'小明',
            'pw': '222',
            'are': '杭州',

        },

        "comment":[
            # "写的很不错",
            # "非常的精彩"
        ]

    }
    return render(request, 'change_implementation.html',context=connect)

change_management/views.py
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse
from django.db import connection
from datetime import datetime


# Create your views here.
def get_corsor():
    return connection.cursor()

def changemanagement(request):
    cursor =get_corsor()
    cursor.execute('select*from change_management')
    changemanagements = cursor.fetchall()
    return render(request, 'change_management.html', context={'changemanagements': changemanagements})

def changemanagement_add(request):
    if request.method =='GET':
        return render(request,'changemanagement_add.html')
    else:
        AssociationTypes = request.POST.get("AssociationTypes")
        AssociatedNumber = request.POST.get("AssociatedNumber")
        Datebase = request.POST.get("Datebase")
        Informant = request.POST.get("Informant")
        ChangeContent = request.POST.get("ChangeContent")
        cursor = get_corsor()
        cursor.execute("insert into change_management(ChangeID,AssociationTypes,AssociatedNumber,Datebase,Informant,FillTime,Reviewer,ReviewStatus,ReviewContent,ChangeContent,AuditTime) value (null,'%s','%s','%s','%s','%s',null, null,null,'%s',null)" % (AssociationTypes, AssociatedNumber, Datebase, Informant, datetime.now(), ChangeContent))
        return redirect(reverse('index_home:index_management'))

def changemanagement_delete (request):
    if request.method == 'POST':
        if 'delete'in request.POST:
            ChangeID =request.POST.get("ChangeID")
            cursor =get_corsor()
            cursor.execute("delete from change_management where ChangeID =%s" %ChangeID)
            return redirect(reverse('index_home:index_management'))

        elif 'editor'in request.POST:
            AssociationTypes = request.POST.get("AssociationTypes")
            AssociatedNumber = request.POST.get("AssociatedNumber")
            Datebase = request.POST.get("Datebase")
            Informant = request.POST.get("Informant")
            ChangeContent = request.POST.get("ChangeContent")
            cursor = get_corsor()
            cursor.execute(
                "update change_management set (ChangeID,AssociationTypes,AssociatedNumber,Datebase,Informant,FillTime,Reviewer,ReviewStatus,ReviewContent,ChangeContent,AuditTime )  value (null,'%s','%s','%s','%s','%s',null, null,null,'%s',null) " % (
                AssociationTypes, AssociatedNumber, Datebase, Informant, datetime.now(), ChangeContent))
            return redirect(reverse('index_home:index_management'))
            return HttpResponse("编辑还没做")
    else:
        raise RuntimeError("删除图书的method错误！")

templates/base.html
{% load my_filter %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
         <title>Title</title>
    {% endblock %}

    <link rel="stylesheet" href="/static/css/base.css">
</head>
<body>
<nav>
    <ul class='nav'>
        <li><a href="{% url 'index_home:index_management' %}">首页</a></li>
{#        <li><a href="{% url 'change_management:bklist' %}">变更提交</a></li>#}
        <li><a href="{% url 'change_management:changemanagement_add' %}">变更提交</a></li>
{#        <li><a href="{% url 'change_management:page' page=3 %}">变更管理</a></li>#}
        <li><a href="{% url 'change_implementation:implementation'%}">变更管理</a></li>
{#        <li><a href="{% url 'change_management:changement' %}">登录</a></li>#}
{#        <li><a href="{% url 'change_management:book_author' %}?id=2">后台管理</a></li>#}
    </ul>
</nav>

    <div class='connect'>
        {% block connect %}
        
        {% endblock %}
    </div>
</body>
</html>

templates/change_implementation.html
{% extends 'base.html' %}
{% load my_filter %}
{% block connect %}
    <link rel="stylesheet" href="/static/css/change_implementation.css">
    <body class ='bo'>
        <table  class="lis">
            <thead>
            <tr>
                <td>序号</td>
                <td>书名</td>
                <td>作者</td>
                <td>价格</td>
                <td>时间</td>
            </tr>
            </thead>

            <tbody>
                {% for book in books %}
                    {% if forloop.first %}
                        <tr style="background: chartreuse">
                    {% elif forloop.last %}
                        <tr style="background: aqua">
                    {% else %}
                        <tr>
                    {% endif %}
                            <td>{{ forloop.counter}}</td>
                            <td>{{ book.name |truncatechars:4}}</td>
                            <td>{{ book.author }}</td>
                            <td>{{ book.price|floatformat:2 }}元</td>
    {#                      <td>{{ book.tody|date:"Y-m-d G:i:s"|default:'未知时间'}}</td>#}
                            <td>{{ book.tody|time_since|default:'未知时间'}}</td>
                {% endfor %}
            </tbody>
        </table>
        <ul class ="ur1">
            {% for comm in comment %}
                <li>{{ comm }}</li>
            {% empty %}
                <li>这里没有评论哦</li>
            {% endfor %}
        </ul>
    </body>
{% endblock %}

templates/change_management.html
{% extends 'base.html' %}
{% load my_filter %}
{% block title %}
    <title>变更管理</title>
{% endblock %}

{% block connect %}
    <link rel="stylesheet" href="{% static '/css/base.css' %}">
<link rel="stylesheet" href="/static/css/change_management.css">
    <body class ='bo'>
        <table  class="lis">
            <thead>
            <tr>
                <th>序号</th>
                <th>变更编号</th>
                <th>关联类型</th>
                <th>关联编号</th>
                <th>数据库</th>
                <th>变更内容</th>
                <th>填报人</th>
                <th>填报时间</th>
                <th>审核人</th>
                <th>审核状态</th>
                <th>审核内容</th>
                <th>审核时间</th>
                <th>编辑</th>
            </tr>
            </thead>

            <tbody>
            {% for changemanagement in changemanagements %}
            
            {% endfor %}
            
                {% for changemanagement in changemanagements %}
                    {% if forloop.first %}
                        <tr style="background: chartreuse">
                    {% elif forloop.last %}
                        <tr style="background: aqua">
                    {% else %}
                        <tr>
                    {% endif %}
                    <td class ='序号'>{{ forloop.counter}}</td>
                    <td class ='00-变更编号'>{{ changemanagement.0}}</td>
                    <td class ='01-关联类型'>{{ changemanagement.1}}</td>
                    <td class ='02-关联编号'>{{ changemanagement.2}}</td>
                    <td class ='03-数据库'>{{ changemanagement.3}}</td>
                    <td class ='09-变更内容'>{{ changemanagement.9}}</td>
                    <td class ='04-填报人'>{{ changemanagement.4}}</td>
                    <td class ='05-填报时间'>{{ changemanagement.5|date:"Y-m-d H:i:s"}}</td>
                    <td class ='06-审核人'>{{ changemanagement.6|default:''}}</td>
                    <td class ='07-审核状态'>{{ changemanagement.7|default:''}}</td>
                    <td class ='08-审核内容'>{{ changemanagement.8|default:''}}</td>
                    <td class ='10-审核时间'>{{ changemanagement.10|date:"Y-m-d H:i:s"}}</td>
                    <td>
                        <form action="{% url 'change_management:changemanagement_delete' %}"method="post">
                            <input type="hidden" name="ChangeID" value="{{ changemanagement.0 }}">
                            <input type="submit"value="编辑"  name="editor">
                            <input type="submit"value="删除" name="delete">
                        </form>

                    </td>

                {% endfor %}
            </tbody>
        </table>
    </body>

{% endblock %}

templates/changemanagement_add.html
{% extends 'base.html' %}
{% block connect %}
    <form action="" method="post">
        <table>
            <tbody>
                <tr>
                    <td>关联类型：</td>
                    <td><input type="text"name="AssociationTypes"></td>
                </tr>
                <tr>
                    <td>关联编号：</td>
                    <td><input type="text"name="AssociatedNumber"></td>
                </tr>
                <tr>
                    <td>数据库：</td>
                    <td><input type="text"name="Datebase"></td>
                </tr>
                <tr>
                    <td>填报人：</td>
                    <td><input type="text"name="Informant"></td>
                </tr>
                <tr>
                    <td>变更内容：</td>
                    <td><input type="text"name="ChangeContent"></td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit"></td>
                </tr>
            </tbody>
        </table>
    </form>
{% endblock %}

templates/footer.html
<p>这是底部</p>

templates/index.html
{% load my_filter %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        .lis{
            overflow:hidden;
            position: absolute;left:20px;top:50px;
        }
        .ur1{
            overflow:hidden;
            position: absolute;left:20px;top:300px;

        }
        .ur2{
          overflow:hidden;
            position: absolute;left:20px;top:200px;
        }

    </style>
</head>
<body>
    {% include "base.html" %}
    <table  class="lis">
        <thead>
        <tr>
            <td>序号</td>
            <td>书名</td>
            <td>作者</td>
            <td>价格</td>
            <td>时间</td>
        </tr>
        </thead>

        <tbody>
            {% for book in books %}
                {% if forloop.first %}
                    <tr style="background: chartreuse">
                {% elif forloop.last %}
                    <tr style="background: aqua">
                {% else %}
                    <tr>
                {% endif %}
                        <td>{{ forloop.counter}}</td>
                        <td>{{ book.name |truncatechars:4}}</td>
                        <td>{{ book.author }}</td>
                        <td>{{ book.price|floatformat:2 }}元</td>
{#                      <td>{{ book.tody|date:"Y-m-d G:i:s"|default:'未知时间'}}</td>#}
                        <td>{{ book.tody|time_since|default:'未知时间'}}</td>
            {% endfor %}
        </tbody>
    </table>
    <ur class ="ur1">
        {% for comm in comment %}
            <li>{{ comm }}</li>
        {% empty %}
            <li>这里没有评论哦</li>
        {% endfor %}
{#    </ur>#}
{#    <ur class ="ur2">#}
{#        {% with books.0 as  ne %}#}
{#            <li>{{ ne }}</li>#}
{#            <li>{{ ne }}</li>#}
{#            <li>{{ ne }}</li>#}
{#            <p>{{ ne }}</p>#}
{#        {% endwith %}#}
{#    </ur>#}
    {% include 'footer.html' %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en"><!-- 把你要显示的内容全部放在页面里 -->
   <!--doctype html> 声明文档类型 html5 ->h5 ->html ->xtml 1.01 DTD
   html ->结构  ->赤裸的孩子
   css  -> 装饰  ->穿着打扮
   js   -> 动作  ->行为举止
   !doctype html ->声明  ->heml5规范
	潜规则，命名 见名知意
-->
 <head><!--和浏览器进行交互 -->
     <meta charset="UTF-8">
    <title>Title</title>
  <meta charset="UTF-8"> <!--字符编码,utf8 万国码-->
  <meta name="Generator" content="editplus"> <!--使用工具生成的-->
  <meta name="Author" content="aoishiori"> <!--作者 -->
  <meta name="Keywords" content="11">  <!--百度关键词匹配 -->
  <meta name="Description" content="仅供公司内部使用">  <!--页面内容描述,百度检索结果页面描述 -->
  <title>Conlin_变更提交系统</title>  <!--网页标题 -->
  <style>/* CSS样式表 */
  *{/* 选中所有标签通配符 清除默认所有样式 */
		margin: 0;
		padding: 0;
  }
  html,body{/*并列*/
	height:100%;/*可视大小，页面有多大，就显示多大*/
  }
  body{
	display:grid;/*网格布局*/
	/*display:flex;/*弹性盒模型,把页面变成盒子/
	justify-content:center;/*水平轴对齐方式 居中对齐/
	align-items:center; /*垂直对齐方式 居中对齐*/
	/*添加一个背景图片 url路径        不平铺   位置、大小*/
	background: src=('/static/1.jpg') no-repeat  center;/*不重叠,居中*/
  }
	.login{/*CSS选择器*/
		/*grid-row:3; /*网格布局：3行/
		grid-column:3;*//*网格布局：3列*/
		width:300px;/*宽度*/
		height:300px;/*高度*/
		margin: auto;
		background-color:#ebf0f1; /*背景颜色：天蓝50a2d6*/
		border-radius:10px;
	}

	.login:before{/*伪元素*/
		content:"";/*激活伪元素的必要因素，填写会显示文字内容，*/
		display:block;
		width:100%;
		height:10px;
		background-image:-webkit-linear-gradient(left,
		#27ae60 0%, #27ae60 20%,
		#8444ad 20%,#8444ad 40%,
		#3498d8 40%,#3498d8 60%,
		#e74c3c 60%,#e74c3c 80%,
		#f1c40f 80%,#f1c40f 100%
		); /*渐变色*/
		border-radius:6px 6px 0px 0px;  /*圆角属性左上，右上 ，左下，右下*/
		/*position:relative;
		bottom:-200px;/     /*上下所在位置*/
	}
	/*.login-head{
		width:100%;
		height:10px;
		background-image:-webkit-linear-gradient(left,
		#27ae60 0%, #27ae60 20%,
		#8444ad 20%,#8444ad 40%,
		#3498d8 40%,#3498d8 60%,
		#e74c3c 60%,#e74c3c 80%,
		#f1c40f 80%,#f1c40f 100%
		); /*渐变色/
		border-radius:6px 6px 0px 0px;  /*圆角属性左上，右上 ，左下，右下/
		/*position:relative;
		bottom:-200px;*/     /*上下所在位置/
	}*/
	/*
		熟悉CSS  .login::before ->经历过IE 是否兼容的写法
		DOM
		0.3秒打开网站
		h1->是主标题 唯一一个，
		h2->标签 副标题，
		h3->商品 主标题
		伪元素 ->性能上有优化，不能被选中。不存在于DOM

	*/

	.title{
		line-height:80px;		/*行高*/
		text-align: center;		/*水平居中*/
		color:#096;				/*颜色*/
		font-size:1.5em;			/*16px  2*16px rem 默认字体的2倍大小，适配写法 不一定要用16px*/
	}
	.login-content{
		display:flex;
		flex-direction:column;/*改变弹性盒方向,column:列 rows：排*/
		justify-content:space-around; /*水平方向等比环绕*/
		align-items:center; /*垂直轴*/
		height:200px;
		background-color:#ccc;
	}
	.login-content input{
		width:80%;
		height:40px;
		border:1px solid #bbb;
		border-radius:6px;/*圆角*/
		outline:none;/*清除点击的默认样式，点击是的外边框*/
		text-indent:1.3em;/*行缩进*/
	}
	.login-content input[type='submit']{/*熟悉选择器：选中input下的sbumit元素*/
		text-indent:0;
		background-color:#e74c3c;
		color:#fff;
	}
  </style>
 </head>
 <body><!--写给用户看的-->
	<div class= "login"><!--盒子标签 宽高大小颜色-->
		<!--<div class ="login-head"></div><--盒子，loging上方的颜色条-->
		<h2 class="title">用户登录</h2>
		<form action="" class="login-content" method ='post'><!--表单-->
		<input type ="text" name ='user' placeholder ='请输入账号'> <!--文本框-->
		<input type ="password" name ='pwd' placeholder ='请输入密码'> <!--密码-->
		<input type ="submit" value ='登录'>
	</div>

 </body>
</html>